[package]
name = "bint"
version = "0.1.0"
authors = ["isaac-holt <isaac_holt@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
num-traits = "0.2.14"